server:
  port: 8181
  
spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://localhost:8070
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/books/**
        - id: issuer-service
          uri: lb://issuer-service
          predicates:
            - Path=/issuer/**
        - id: oauth-server
          uri: lb://oauth-server
          predicates:
            - Path=/oauth/**
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
profiles:
  active: dev
  config: 
    import : "optional:configserver:"
     
      

