server:
  port: 8090
  
  
spring:
  application:
    name: book-service
    
  profiles:
    active: dev
  config: 
    import : "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8010
