server:
  servlet:
    context-path: /bookms
  port: 8010
  
  
spring:
  application:
    name: book-service
  
  profiles:
    active: dev
  config: 
    import : "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8070

  datasource:
    url: jdbc:h2:mem:books-db
    username: booksapp
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
      health:
        show-details: always  

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8030/oauth/check_token//
      token-type: Bearer
    client:
      client-id: bookapp
      client-secret: 123456
      grant-type: client_credentials
      scope: read
      
springdoc:
  swagger-ui:
    path: /swagger-ui.html
     