server:
  port: 8020
  
  
spring:
  application:
    name: issuer-service
    
  profiles:
    active: dev
  config: 
    import : "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8070
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8030/oauth/check_token//
      token-type: Bearer
    client:
      client-id: gateway
      client-secret: 123456
      grant-type: client_credentials
      scope: read

