server:
  port: 8030

spring:
  application:
    name: oauth-server
  profiles:
    active: dev
  config: 
    import : "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8070

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/