server:
  port: 8030

spring:
  application:
    name: oauth-server
  profiles:
    active: dev
  config: 
    import : "optional:configserver:"
  cloud:
    config:
      uri: http://host.docker.internal:8070

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true