server:
  port: 8010
 
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/geistFahrer/amazing-book-ms-config-repo
          search-paths:
          - book-service
          
logging:
  level:
    root: DEBUG
          
