server:
  port: 8070
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/geistFahrer/amazing-book-ms-config-repo
          search-paths:
          - book-service
          - issuer-service
          - api-gateway
          - oauth-server
          - service-registry
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
          
          
